name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
          cache: true
          cache-dependency-path: |
            **/*.csproj
            Directory.Build.props

      - name: Restore
        run: dotnet restore .\FoToolbox.sln

      - name: Build
        run: dotnet build .\FoToolbox.sln -c Release --no-restore

      - name: Test
        run: dotnet test .\FoToolbox.sln -c Release --no-build --collect:"XPlat Code Coverage" --blame-hang --blame-hang-timeout 150s --blame-hang-dump-type mini --results-directory ${{ github.workspace }}\TestResults

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ${{ github.workspace }}\TestResults
          if-no-files-found: ignore

      - name: Vulnerable packages
        run: dotnet list .\FoToolbox.sln package --vulnerable --include-transitive
